executor:
  name: nodejs
  options:
    entry: main.js
inputs_def:
  - handle: latex
    json_schema:
      type: string
outputs_def:
  - handle: svgString
    json_schema:
      type: string
icon: ":fa6-solid:image:"
title: Latex To Image
description: |-
  output latex as svg image
  将 latex 转换为svg 图片
